export const LOAD_BIRDS_REQUEST = 'LOAD_BIRDS_REQUEST'
export const LOAD_BIRDS_SUCCESS = 'LOAD_BIRDS_SUCCESS'
export const LOAD_BIRDS_FAILURE = 'LOAD_BIRDS_FAILURE'

export const ADD_BIRD_REQUEST = 'ADD_BIRD_REQUEST'
export const ADD_BIRD_SUCCESS = 'ADD_BIRD_SUCCESS'
export const ADD_BIRD_FAILURE = 'ADD_BIRD_FAILURE'